server:
  servlet:
    context-path: /demo

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration, org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration, org.springframework.boot.autoconfigure.data.jdbc.JdbcRepositoriesAutoConfiguration, org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  application:
    name: demo
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        enabled: false
        register: false
      enabled: true
    discovery:
      enabled: false
